baseurl = "/"
languageCode = "en-us"
title = "DASC blog"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$", "\\.csv$", "\\.jpg$", "\\.png$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/arbeger"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/anthony_beger"
[[menu.main]]
    name = "Resume"
    url = "/my_resume.pdf"
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/anthony-beger-1025601ba/"
    
[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "me.jpg"
    width = 50
    height = 50
    alt = "Logo"

