---
title: "Untitled"
output: pdf_document
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(ggplot2)
library(tidyverse)
library(readxl)
library(ggthemes)

attendance <- readr::read_csv(here::here("data", "tidytuesday", "attendence.csv"))
standings <- readr::read_csv(here::here("data", "tidytuesday", "standings.csv"))
games <- readr::read_csv(here::here("data", "tidytuesday", "games.csv"))

```

```{r}
dat <- attendance %>%
  left_join(standings, by = c("team", "team_name", "year"))

ggplot(dat, aes(x = wins, y = home)) +
  geom_point(aes(color = playoffs)) +
  geom_smooth(method = "lm") +
  labs(x = "Wins", y = "Total Attendence at Home Games") +
  ggtitle("Home Game Attendence vs Wins and Playoff Births") +
  theme_economist() +
  theme(plot.title = element_text(hjust = 0.35))

ggplot(dat, aes(x = playoffs, y = home)) +
  geom_boxplot() +
  labs(x = "Playoff Birth", y = "Total Attendence at Home Games") +
  ggtitle("Home Game Attendence vs Playoff Births") +
  theme_economist() +
  theme(plot.title = element_text(hjust = 0.35))

ggplot(dat, aes(x = sb_winner, y = home)) +
  geom_boxplot() +
  labs(x = "Superbowl Winner", y = "Total Attendence at Home Games") +
  ggtitle("Home Game Attendence vs Superbowl Winners") +
  theme_economist() +
  theme(plot.title = element_text(hjust = 0.35))
```


```{r}
games <- games %>%
  mutate(week = as.numeric(week))

games %>%
  left_join(attendance, by = c("home_team_city" = "team", "home_team_name" = "team_name", "year", "week")) %>%
  filter(day == c("Sun", "Mon", "Thu")) %>%
  group_by(day, time) %>%
  summarize(avr_attendance = mean(weekly_attendance, na.rm = TRUE))
```


```{r}
dat <- attendance %>%
  left_join(standings, by = c("team", "team_name", "year"))
  
ggplot(dat, aes(x = offensive_ranking, y = home)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(x = "Offensive Ranking", y = "Total Attendance at Home Games") +
  ggtitle("Home Game Attendance vs Offensive Ranking") +
  theme_economist()

ggplot(dat, aes(x = points_for, y = home)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(x = "Points Scored in a Season", y = "Total Attendance at Home Games") +
  ggtitle("Home Game Attendance vs Points Scored") +
  theme_economist() +
  theme(plot.title = element_text(hjust = 0.35))

ggplot(dat, aes(x = defensive_ranking, y = home)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(x = "Defensive Ranking", y = "Total Attendance at Home Games") +
  ggtitle("Home Game Attendance vs Defensive Ranking") +
  theme_economist() +
  theme(plot.title = element_text(hjust = 0.35))

ggplot(dat, aes(x = points_against, y = home)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(x = "Points Given Up in a Season", y = "Total Attendance at Home Games") +
  ggtitle("Home Game Attendance vs Points Given Up") +
  theme_economist() +
  theme(plot.title = element_text(hjust = 0.35))
```
