---
title: "DASC 1104 Project Proposal"
author: "Anthony Beger"
output: pdf_document
---

<link href="/rmarkdown-libs/anchor-sections/anchor-sections.css" rel="stylesheet" />
<script src="/rmarkdown-libs/anchor-sections/anchor-sections.js"></script>


<div id="my-blog-link" class="section level2">
<h2>1 My blog link</h2>
<p>My blog is available at <a href="https://arbeger-blog.netlify.app/">https://arbeger-blog.netlify.app/</a></p>
<pre class="r"><code>library(here)
library(ggplot2)
library(tidyverse)
library(readxl)

attendance &lt;- readr::read_csv(here::here(&quot;data&quot;, &quot;tidytuesday&quot;, &quot;attendence.csv&quot;))
standings &lt;- readr::read_csv(here::here(&quot;data&quot;, &quot;tidytuesday&quot;, &quot;standings.csv&quot;))
games &lt;- readr::read_csv(here::here(&quot;data&quot;, &quot;tidytuesday&quot;, &quot;games.csv&quot;))

glimpse(attendance)</code></pre>
<pre><code>## Observations: 10,846
## Variables: 8
## $ team              &lt;chr&gt; &quot;Arizona&quot;, &quot;Arizona&quot;, &quot;Arizona&quot;, &quot;Arizona&quot;, &quot;Arizon…
## $ team_name         &lt;chr&gt; &quot;Cardinals&quot;, &quot;Cardinals&quot;, &quot;Cardinals&quot;, &quot;Cardinals&quot;,…
## $ year              &lt;dbl&gt; 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 200…
## $ total             &lt;dbl&gt; 893926, 893926, 893926, 893926, 893926, 893926, 893…
## $ home              &lt;dbl&gt; 387475, 387475, 387475, 387475, 387475, 387475, 387…
## $ away              &lt;dbl&gt; 506451, 506451, 506451, 506451, 506451, 506451, 506…
## $ week              &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, …
## $ weekly_attendance &lt;dbl&gt; 77434, 66009, NA, 71801, 66985, 44296, 38293, 62981…</code></pre>
<pre class="r"><code>glimpse(standings)</code></pre>
<pre><code>## Observations: 638
## Variables: 15
## $ team                 &lt;chr&gt; &quot;Miami&quot;, &quot;Indianapolis&quot;, &quot;New York&quot;, &quot;Buffalo&quot;, …
## $ team_name            &lt;chr&gt; &quot;Dolphins&quot;, &quot;Colts&quot;, &quot;Jets&quot;, &quot;Bills&quot;, &quot;Patriots&quot;…
## $ year                 &lt;dbl&gt; 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, …
## $ wins                 &lt;dbl&gt; 11, 10, 9, 8, 5, 13, 12, 9, 7, 4, 3, 12, 11, 7, …
## $ loss                 &lt;dbl&gt; 5, 6, 7, 8, 11, 3, 4, 7, 9, 12, 13, 4, 5, 9, 10,…
## $ points_for           &lt;dbl&gt; 323, 429, 321, 315, 276, 346, 333, 321, 367, 185…
## $ points_against       &lt;dbl&gt; 226, 326, 321, 350, 338, 191, 165, 255, 327, 359…
## $ points_differential  &lt;dbl&gt; 97, 103, 0, -35, -62, 155, 168, 66, 40, -174, -2…
## $ margin_of_victory    &lt;dbl&gt; 6.1, 6.4, 0.0, -2.2, -3.9, 9.7, 10.5, 4.1, 2.5, …
## $ strength_of_schedule &lt;dbl&gt; 1.0, 1.5, 3.5, 2.2, 1.4, -1.3, -2.5, -0.2, -1.4,…
## $ simple_rating        &lt;dbl&gt; 7.1, 7.9, 3.5, 0.0, -2.5, 8.3, 8.0, 3.9, 1.1, -1…
## $ offensive_ranking    &lt;dbl&gt; 0.0, 7.1, 1.4, 0.5, -2.7, 1.5, 0.0, 0.6, 3.2, -8…
## $ defensive_ranking    &lt;dbl&gt; 7.1, 0.8, 2.2, -0.5, 0.2, 6.8, 8.0, 3.3, -2.1, -…
## $ playoffs             &lt;chr&gt; &quot;Playoffs&quot;, &quot;Playoffs&quot;, &quot;No Playoffs&quot;, &quot;No Playo…
## $ sb_winner            &lt;chr&gt; &quot;No Superbowl&quot;, &quot;No Superbowl&quot;, &quot;No Superbowl&quot;, …</code></pre>
<pre class="r"><code>glimpse(games)</code></pre>
<pre><code>## Observations: 5,324
## Variables: 19
## $ year           &lt;dbl&gt; 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, …
## $ week           &lt;chr&gt; &quot;1&quot;, &quot;1&quot;, &quot;1&quot;, &quot;1&quot;, &quot;1&quot;, &quot;1&quot;, &quot;1&quot;, &quot;1&quot;, &quot;1&quot;, &quot;1&quot;, &quot;1&quot;,…
## $ home_team      &lt;chr&gt; &quot;Minnesota Vikings&quot;, &quot;Kansas City Chiefs&quot;, &quot;Washington…
## $ away_team      &lt;chr&gt; &quot;Chicago Bears&quot;, &quot;Indianapolis Colts&quot;, &quot;Carolina Panth…
## $ winner         &lt;chr&gt; &quot;Minnesota Vikings&quot;, &quot;Indianapolis Colts&quot;, &quot;Washington…
## $ tie            &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
## $ day            &lt;chr&gt; &quot;Sun&quot;, &quot;Sun&quot;, &quot;Sun&quot;, &quot;Sun&quot;, &quot;Sun&quot;, &quot;Sun&quot;, &quot;Sun&quot;, &quot;Sun&quot;…
## $ date           &lt;chr&gt; &quot;September 3&quot;, &quot;September 3&quot;, &quot;September 3&quot;, &quot;Septembe…
## $ time           &lt;time&gt; 13:00:00, 13:00:00, 13:01:00, 13:02:00, 13:02:00, 13:…
## $ pts_win        &lt;dbl&gt; 30, 27, 20, 36, 16, 27, 21, 14, 21, 41, 9, 23, 20, 16,…
## $ pts_loss       &lt;dbl&gt; 27, 14, 17, 28, 0, 7, 16, 10, 16, 14, 6, 0, 16, 13, 36…
## $ yds_win        &lt;dbl&gt; 374, 386, 396, 359, 336, 398, 296, 187, 395, 425, 233,…
## $ turnovers_win  &lt;dbl&gt; 1, 2, 0, 1, 0, 0, 1, 2, 2, 3, 0, 1, 1, 0, 3, 4, 1, 0, …
## $ yds_loss       &lt;dbl&gt; 425, 280, 236, 339, 223, 249, 278, 252, 355, 167, 255,…
## $ turnovers_loss &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 3, 4, 2, 4, 6, 2, 1, 0, 1, 3, 3, …
## $ home_team_name &lt;chr&gt; &quot;Vikings&quot;, &quot;Chiefs&quot;, &quot;Redskins&quot;, &quot;Falcons&quot;, &quot;Steelers&quot;…
## $ home_team_city &lt;chr&gt; &quot;Minnesota&quot;, &quot;Kansas City&quot;, &quot;Washington&quot;, &quot;Atlanta&quot;, &quot;…
## $ away_team_name &lt;chr&gt; &quot;Bears&quot;, &quot;Colts&quot;, &quot;Panthers&quot;, &quot;49ers&quot;, &quot;Ravens&quot;, &quot;Jagu…
## $ away_team_city &lt;chr&gt; &quot;Chicago&quot;, &quot;Indianapolis&quot;, &quot;Carolina&quot;, &quot;San Francisco&quot;…</code></pre>
</div>
<div id="nfl-attendence" class="section level2">
<h2>2 NFL attendence</h2>
<p>For this project, I will be examining the NFL attendance data from the <code>attendance.csv</code> file on the Tidy Tuesday Website. The data consists of 10,846 observations and 8 variables. The dataset shows the the total attendance and weekly attendance for every NFL team dating back to the 2000 NFL season.</p>
<p>Another dataset that I will be using to explore NFL attendence is the <code>standings.csv</code> file from the Tidy Tuesday website. The data consists of 638 observations and 15 variables. Some of the variables in this dataset show how well each NFL team preformed in each season since 2000, these variables include the number of <code>wins</code> and <code>loss</code> as well as whether each team made the <code>playoffs</code> or won the Superbowl in the <code>sb_winner</code> variable. This dataset also represents how good each team preformed on offense and defense by having <code>points_for</code> and <code>points_against</code> variables as well as <code>offense_ranking</code> and <code>defense_ranking</code>. This data will help me see if there is a correltaion between team success and attendance.</p>
<p>Lastly, I will be using the <code>games.csv</code> file from the Tidy Tuesday website. The data consists of 5,324 observations and 19 variables. The data shows the outcomes of every NFL game dating back to the 2000 NFL season. The <code>home_team</code> , <code>away_team</code>, and <code>winner</code> variables will be useful to see if there is any sort of home field advantage in the NFL. The <code>day</code>, <code>date</code>, and <code>time</code> variables will be useful to see if NFL games played on different times and dates have different amounts of attendance.</p>
<p>Question 1 : Do playoff teams have more attendance at their home games than non-playoff teams? If so, does the superbowl winner usually lead the league in attendance? To test this, I will join the attendance dataset and the standings dataset to be able to compare the attendance data and whether or not each team made the playoffs. Then, I will creat some plots with the data.</p>
<p>Question 2 : When is the optimal time and day for a NFL game to recieve the highest attendance? To find this, I will join the attendance dataset and the games dataset to compare attendances over different times and dates. I will get the average attendence for each time and day and most likely create a bar graph so that the attendances can be easily compared.</p>
<p>Question 3 : Do teams with a good offense attract more attendence? If not, good defense, or does it not matter? To test this, I will join the attendance dataset and the standings dataset to be able to compare attendance data with offensive and defensive data for each team. I will then make some plots to see if there are any correlations.</p>
<p>Question 4 : To be determined.</p>
</div>
<div id="european-energy-data-analysis" class="section level2">
<h2>3 European Energy data analysis</h2>
<pre class="r"><code>energy_types &lt;- readr::read_csv(here::here(&quot;data&quot;, &quot;tidytuesday&quot;, &quot;energy_types.csv&quot;))
country_totals &lt;- readr::read_csv(here::here(&quot;data&quot;, &quot;tidytuesday&quot;, &quot;country_totals.csv&quot;))

glimpse(energy_types)</code></pre>
<pre><code>## Observations: 296
## Variables: 7
## $ country      &lt;chr&gt; &quot;BE&quot;, &quot;BE&quot;, &quot;BE&quot;, &quot;BE&quot;, &quot;BE&quot;, &quot;BE&quot;, &quot;BE&quot;, &quot;BE&quot;, &quot;BG&quot;, &quot;B…
## $ country_name &lt;chr&gt; &quot;Belgium&quot;, &quot;Belgium&quot;, &quot;Belgium&quot;, &quot;Belgium&quot;, &quot;Belgium&quot;, &quot;…
## $ type         &lt;chr&gt; &quot;Conventional thermal&quot;, &quot;Nuclear&quot;, &quot;Hydro&quot;, &quot;Pumped hydr…
## $ level        &lt;chr&gt; &quot;Level 1&quot;, &quot;Level 1&quot;, &quot;Level 1&quot;, &quot;Level 2&quot;, &quot;Level 1&quot;, &quot;…
## $ `2016`       &lt;dbl&gt; 30728.00, 41430.00, 1476.00, 1110.00, 5340.00, 3070.00, …
## $ `2017`       &lt;dbl&gt; 31316.000, 40128.500, 1360.900, 1093.200, 6387.900, 3264…
## $ `2018`       &lt;dbl&gt; 30092.635, 26995.628, 1239.248, 983.190, 7177.346, 3488.…</code></pre>
<pre class="r"><code>glimpse(country_totals)</code></pre>
<pre><code>## Observations: 185
## Variables: 7
## $ country      &lt;chr&gt; &quot;BE&quot;, &quot;BE&quot;, &quot;BE&quot;, &quot;BE&quot;, &quot;BE&quot;, &quot;BG&quot;, &quot;BG&quot;, &quot;BG&quot;, &quot;BG&quot;, &quot;B…
## $ country_name &lt;chr&gt; &quot;Belgium&quot;, &quot;Belgium&quot;, &quot;Belgium&quot;, &quot;Belgium&quot;, &quot;Belgium&quot;, &quot;…
## $ type         &lt;chr&gt; &quot;Total net production&quot;, &quot;Imports&quot;, &quot;Exports&quot;, &quot;Energy ab…
## $ level        &lt;chr&gt; &quot;Total&quot;, &quot;Total&quot;, &quot;Total&quot;, &quot;Total&quot;, &quot;Total&quot;, &quot;Total&quot;, &quot;T…
## $ `2016`       &lt;dbl&gt; 82520.000, 14648.000, 8465.000, 1475.000, 87228.000, 412…
## $ `2017`       &lt;dbl&gt; 82948.500, 14189.400, 8167.800, 1485.400, 87484.700, 413…
## $ `2018`       &lt;dbl&gt; 69212.347, 21635.908, 4308.347, 1347.901, 85192.007, 417…</code></pre>
<p>Using data that is available on the Tidy Tuesday website on European Energy, I will investigate the energy usage among European countries with an emphasis on which countries are the best at using renewable energy. I will be examining data from the <code>energy_types.csv</code> file from the Tidy Tuesday website. The data consists of 296 observations and 7 variables. The data displays each the energy production from each European country from 2016-2018 and breaks it down by how much energy was produced by conventional thermal, nuclear, hydroelectric, pumped hydroelectric, wind, solar, geothermal, and other.</p>
<p>The second dataset I will use to explore European Energy production is the <code>country_totals.csv</code> file from the Tidy Tuesday website. The data consists of 185 observations and 7 variables. The data displays the total energy consumption of each European country from
2016-2018 as well as the total energy production of each country.</p>
<p>Question 1 : Which European country has the largest percentage of their total energy production made up of renewables? To find this, I will join the energy types and country totals datasets. I will also mutate the dataset to combine all of types of energy production that are renewable. Then I will compare the amount of energy produced by renewables in each country in 2018 with their total energy production to find the country with the highest percentage renewable.</p>
<p>Question 2 : Which European country has made the biggest shift towards renewable energy since 2016? To find this, I will join the energy types and country totals datasets. I will also mutate the dataset to combine all of types of energy production that are renewable. Then I will compare the percentage of each countries total energy production was renewable in 2016 vs. 2018 and see which country made the biggest jump.</p>
<p>Question 3 : Is there a correlation between the European countries with the biggest energy outputs and using more convential thermal energy? To test this, I will join the energy types and country totals datasets. Then I will compare the countries with large total energy outputs with ones that have smaller outputs and put the results on a plot so I can easily see if there is any correlation.</p>
<p>Question 4 : To be determined.</p>
</div>
